name: jawhara
description: E-commerce project

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.13+18

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.3
  flutter_localizations:
    sdk: flutter
  flutter_translate: ^3.0.1
  shared_preferences: ^2.0.8
  stacked: ^2.1.7
  stacked_services: ^0.8.6
  provider: ^5.0.0
  get_it: ^7.1.3
  connectivity: ^3.0.6
  flutter_spinkit: ^4.1.2+1
  bot_toast: ^4.0.1
  dio: ^4.0.0
  chewie: ^1.2.2
#  dio_http_cache: ^0.2.11
  flutter_widget_from_html: ^0.7.0
  carousel_slider: ^4.0.0
  page_transition: ^2.0.4
  bubble_tab_indicator: ^0.1.6
  smooth_star_rating: 1.1.1
  expandable: ^5.0.1
  hexcolor: ^2.0.5
  date_format: ^2.0.4
  flutter_vector_icons: ^1.0.0
  google_sign_in: ^5.1.1
  flutter_facebook_auth: ^3.5.2
  the_apple_sign_in: ^1.1.1
  badges: ^2.0.1
#  credit_card: ^0.1.8
  dropdown_search: ^1.0.3
  credit_card_validator: ^2.0.0
  share: ^2.0.4
  full_screen_image: ^1.0.2
  pinch_zoom_image_last: ^0.4.1
  refresh_loadmore: ^2.0.5
  after_layout: ^1.1.0
  flutter_gifimage: ^1.0.1
  flutter_swiper: ^1.1.6
  flutter_html: ^2.1.5
  font_awesome_flutter: ^9.1.0
  extended_image: ^5.1.2
  cached_network_image: ^3.1.0
  flutter_svg: ^0.22.0
  url_launcher: ^6.0.12
  webview_flutter: ^2.1.1
#  flutter_webview_plugin: ^0.4.0
#  pagination_view: ^1.0.4+2
  loadmore: ^2.0.1
#  qr_code_scanner: ^1.0.0-alpha.1
  firebase_core: ^1.7.0
  firebase_messaging: ^10.0.8
  flutter_local_notifications: ^9.0.0
  firebase_remote_config: ^0.11.0+1
  package_info: ^2.0.2
  agconnect_remote_config: ^1.2.0+300
  auto_size_text: ^2.1.0
  pull_to_refresh: ^2.0.0
  intl: ^0.17.0
  firebase_dynamic_links: ^2.0.10
  uni_links: ^0.5.1
  device_info: ^2.0.2
  fcm_config: ^3.1.3
  scrollable_positioned_list: ^0.2.2
  youtube_metadata: ^1.0.1
  flutter_animator: ^3.2.0

#  custom_navigator:
#    git:
#      url: https://github.com/kjawadDeveloper/Custom-navigator.git



dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^1.3.1

flutter_native_splash:
  color: "#333333"
  android_disable_fullscreen: true
  fill: true


# Run this script to generate the app icon: flutter pub run flutter_launcher_icons:main
#ic_launcher, launcher_icon
flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/app_logo2.jpg"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/i18n/
    - assets/images/

  fonts:
    - family: Cairo
      fonts:
#        - asset: assets/fonts/Cairo/Cairo-Black.ttf
#        - asset: assets/fonts/Cairo/Cairo-Bold.ttf
#        - asset: assets/fonts/Cairo/Cairo-ExtraLight.ttf
#        - asset: assets/fonts/Cairo/Cairo-Light.ttf
        - asset: assets/fonts/Cairo/Cairo-Regular.ttf
#        - asset: assets/fonts/Cairo/Cairo-SemiBold.ttf
    - family: Tajawal
      fonts:
#        - asset: assets/fonts/Tajawal/Tajawal-Black.ttf
#        - asset: assets/fonts/Tajawal/Tajawal-Bold.ttf
#        - asset: assets/fonts/Tajawal/Tajawal-ExtraBold.ttf
#        - asset: assets/fonts/Tajawal/Tajawal-ExtraLight.ttf
#        - asset: assets/fonts/Tajawal/Tajawal-Light.ttf
        - asset: assets/fonts/Tajawal/Tajawal-Regular.ttf
    # Icons font
    # go to https://www.fluttericon.com/ and upload the svg files in assets/icons and download the new dart file and font
    - family: Icomoon
      fonts:
        - asset: assets/fonts/icomoon/icomoon.ttf
