import 'package:firebase_dynamic_links/firebase_dynamic_links.dart';

import '../config/dynamic_link.dart';

class DynamicLinkService {
  Future generateFirebaseDynamicLinkForProductDetails(
      String lang, String productId,
      {bool shortLink = false}) {
    DynamicLinkParameters parameters = DynamicLinkParameters(
        uriPrefix: firebaseDynamicLinkConfig['uriPrefix'],
        link: Uri.parse(
            "${firebaseDynamicLinkConfig['link'].toString().replaceAll('LANG', lang).replaceAll('PRODUCT_ID', productId)}"),
        androidParameters: AndroidParameters(
          packageName: firebaseDynamicLinkConfig['androidPackageName'],
          minimumVersion: firebaseDynamicLinkConfig['androidAppMinimumVersion'],
        ),
        iosParameters: IosParameters(
          bundleId: firebaseDynamicLinkConfig['iOSBundleId'],
          minimumVersion: firebaseDynamicLinkConfig['iOSAppMinimumVersion'],
          appStoreId: firebaseDynamicLinkConfig['iOSAppStoreId'],
        ));

    final Future dynamicUrl =
        shortLink ? parameters.buildShortLink() : parameters.buildUrl();
    // printLog(
    //     '[dynamic_link] Your Autogenerated Firebase Dynamic Link: $dynamicUrl');
    return dynamicUrl;
  }
}
